version: '3.1'

volumes:
  portainer_data:
    driver: local
  qbittorrent_config:
    driver: local
  nextcloud_config:
    driver: local

services:
  nginxproxymanager:
    container_name: 'nginxproxymanager'
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ~/volumes/nginx/data:/data
      - ~/volumes/nginx/letsencrypt:/etc/letsencrypt

  postgresql:
    container_name: postgresql
    restart: unless-stopped
    image: postgres:15-bookworm
    volumes:
      - ~/volumes/databases/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  portainer:
    container_name: 'portainer'
    image: 'portainer/portainer-ce:latest'
    restart: unless-stopped
    ports:
      - '8000:8000'
      - '9443:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    depends_on:
      - nginxproxymanager

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8081
    volumes:
      - qbittorrent_config:/config
      - ~/share2/torrents:/downloads
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    depends_on:
      - nginxproxymanager

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - nextcloud_config:/config
      - /disk2/files/volumes/nextcloud/data:/data
    depends_on:
      - nginxproxymanager

networks:
  default:
    name: main-net
